# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=false

# AndroidX
android.useAndroidX=true

# Kotlin
kotlin.code.style=official

# Android Build
android.nonTransitiveRClass=true
android.enableJetifier=false

# Java toolchain (自动下载 JDK 17)
org.gradle.java.installations.auto-download=true
